### ISSUE TITLE
What is the path I need to use to import Plekan into my project? 

### ISSUE THREAD

**Issue by retrogradeMT** [abdullah/plekan#10]
I am having trouble importing plekan into my project. 

    After npm install plekan --save, 

I tried to import it three different ways:

    import plekan from 'plekan'
    import plekan from './plekan.js'
    import {editor} from './plekan.'

but I get this error, or the equivalent every time: 

    Module not found: Error: Can't resolve 'plekan'

**Comment by abdullah** [comment]
Hi @retrogradeMT , I'm sorry to say that we forgot to remove the `docs` line from .npmignore. Reinstalling plekan version 1.2.2 will solve the problem.
