### ISSUE TITLE
Integrate into an existing project

### ISSUE THREAD

**Issue by jasonlfunk** [abdullah/plekan#11]
Merhaba -

I'm looking to replace ContentBuilder with this in an existing project.
But it appears that this is an entire app, not a component I can bring in. Is that true?
What would it take to make it a standalone component?

**Comment by abdullah** [comment]
Hi @jasonlfunk , It isn't true, you can use plekan as a module. 
Please, check documentation https://github.com/abdullah/plekan/wiki

Also, I wrote another content builder similar to plekan. But it is still under development. It name is [Leylim](https://github.com/abdullah/leylim)
