### ISSUE TITLE
demo has image in 404

### ISSUE THREAD

**Issue by lexoyo** [abdullah/plekan#4]
Hello
The demo loads urls like this `https://abdullah.github.io/static/thumbnails/plekanmodule1.png` which are 404
![screenshot from 2016-11-16 10-44-13](https://cloud.githubusercontent.com/assets/715377/20342236/f0ca3032-abe9-11e6-842f-d790dd7c2a06.png)

**Comment by abdullah** [comment]
Yep! I updated.
