### ISSUE TITLE
The SASS Loader not found

### ISSUE THREAD

**Issue by tantv** [abdullah/plekan#7]
Hi @abdullah,

I updated to v2 and install it as your guideline but it doesn't work.
I checked and see we need install the sass-loader before we run **npm run dev**

`npm install sass-loader node-sass webpack --save-dev`

And one more thing, we don't have the task for the command **npm run build** or **npm run build --report**, we just have 4 tasks in package.json **dev, start, release and lint**

Regards,

**Comment by abdullah** [comment]
Hi @tantv,

Thanks for reporting this problem,
I'm not sure we need `build` or` build --report` command. Because plekan is only plugin, why did you think this necessary?

**Comment by tantv** [comment]
Hi @abdullah,

Maybe you misunderstand my comment about the task **npm run build**, I see it on the README file and I confused why we need it :)

**Comment by abdullah** [comment]
Ohhh I have forgotten changing readme :(
